### ISSUE TITLE
Incorporate O*NET Elements

### ISSUE THREAD

**Issue by NKeleher** [ripl-org/pyresparser#1]
We want to build out the named entity recognition to detect:

- [ ] ONET Knowledge (https://www.onetcenter.org/dictionary/25.1/excel/knowledge.html)
- [ ] ONET Skills (https://www.onetcenter.org/dictionary/25.1/excel/skills.html)
- [ ] ONET Abilities (https://www.onetcenter.org/dictionary/25.1/excel/abilities.html)
- [ ] ONET Technology Skills (https://www.onetcenter.org/dictionary/25.1/excel/technology_skills.html)
- [ ] ONET Tools Used (https://www.onetcenter.org/dictionary/25.1/excel/tools_used.html)

We may want to identify each category from the O*NET hierarchy separately. As a first attempt, let's use the 

I also think we may want to set up our own curated set of skills (and/or include EMSI skills).

**Comment by m-goggins** [comment]
I added all the ONET skills to a new csv called "combined_skills_onet.csv" in the mg_resume_parser branch

**Comment by m-goggins** [comment]
Added in ONET tools so now we parse:

- ONET Abilities
- ONET Knowledge
- ONET Skills
- ONET Tech Skills
- ONET Tools
- ONET Job Titles
- ONET Alternate Job Titles
- ONET Short Job Titles

- EMSI Soft Skills
- EMSI Hard Skills
- EMSI Certificates 

All of the ONET job titles (short and alternate too) and ONET tools are tied to SOC codes in their JSON files that are saved to the Google Drive.
