### ISSUE TITLE
Purge code of nltk and replace with spaCy implementation

### ISSUE THREAD

**Issue by NKeleher** [ripl-org/pyresparser#2]
Several instances in this code use nltk. To minimize the number of packages and memory necessary, we should get replace any usage of nltk with spaCy.

Examples:
- utils.extract_experience() https://github.com/ripl-org/pyresparser/blob/36f1242fbc0637a6633371ca81cf1aea4fa7497e/pyresparser/utils.py#L451
    - uses WordNetLemmatizer, stopwords, word_tokenizer, RegexpParser
- constants.py https://github.com/ripl-org/pyresparser/blob/36f1242fbc0637a6633371ca81cf1aea4fa7497e/pyresparser/constants.py#L25
    - uses stopwords 
- RegexpParser https://github.com/ripl-org/pyresparser/blob/36f1242fbc0637a6633371ca81cf1aea4fa7497e/pyresparser/utils.py#L473

**Comment by m-goggins** [comment]
No longer using nltk anywhere
