### ISSUE TITLE
Revisions to constants

### ISSUE THREAD

**Issue by NKeleher** [ripl-org/pyresparser#3]
We want to update the following constants in the constants.py script

- NAME_PATTERN - allow for more flexible name patterns (i.e. multiple names). Currently only allows for two names (first and last)
- EDUCATION - expand out to include more degrees (e.g. Ph.D., B.S., MBA,...)
- RESUME_SECTIONS_PROFESSIONAL - expand out the resume sections that we want to identify
- RESUME_SECTIONS_GRAD - expand out the resume sections that we want to identify

**Comment by m-goggins** [comment]
EDUCATION - list of higher ed degrees and abbreviations from NSC[ here](https://studentclearinghouse.info/verificationshelp/knowledge-base/degree-titles-and-abbreviations/):

**Comment by NKeleher** [comment]
@m-goggins - would still be great to extract education and job titles from resumes. Please use the lay job titles mentioned by @dmolitor in our Friday team meeting.

**Comment by m-goggins** [comment]
Done; there are no longer constants in the resume parser (that was a pyresparser design) but the job titles are loaded in as patterns.
